// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0xpMZBtT7kUoWnmEN9mm-n-cdnwi7WsY',
    appId: '1:535753950977:web:48235e382f64eddf833d00',
    messagingSenderId: '535753950977',
    projectId: 'tarif-kosesi',
    authDomain: 'tarif-kosesi.firebaseapp.com',
    storageBucket: 'tarif-kosesi.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPtojJf58NFY0tMcIBmwLw_Vq_t7iS9fU',
    appId: '1:535753950977:android:a66dc2bdc01d9aee833d00',
    messagingSenderId: '535753950977',
    projectId: 'tarif-kosesi',
    storageBucket: 'tarif-kosesi.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGKCEkuL30jLYC4_dNGN5DV6771G8OgKY',
    appId: '1:535753950977:ios:a4d6195bdeb16f68833d00',
    messagingSenderId: '535753950977',
    projectId: 'tarif-kosesi',
    storageBucket: 'tarif-kosesi.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGKCEkuL30jLYC4_dNGN5DV6771G8OgKY',
    appId: '1:535753950977:ios:089ed54afd78b0f7833d00',
    messagingSenderId: '535753950977',
    projectId: 'tarif-kosesi',
    storageBucket: 'tarif-kosesi.appspot.com',
    iosBundleId: 'com.example.flutterApplication2.RunnerTests',
  );
}
